COLUM ROOMTYPE FORMAT A8;
SET PAGESIZE 30;
SET LINESIZE 200;

SELECT COUNT(ROOM.ROOMTYPE) AS FREQUENCY, ROOMTYPE AS ROOMSIZE
FROM ROOM
JOIN BOOKING
ON ROOM.ROOMID = BOOKING.ROOMID
GROUP BY ROOMTYPE
ORDER BY COUNT(ROOM.ROOMTYPE) DESC;