COLUMN ROOMTYPE FORMAT A8;
SET PAGESIZE 30;
SET LINESIZE 200;

DROP VIEW listRoomCount;

CREATE VIEW listRoomCount AS
SELECT COUNT(ROOM.ROOMTYPE) AS FREQUENCY, ROOMTYPE
FROM ROOM
JOIN BOOKING
ON ROOM.ROOMID = BOOKING.ROOMID
GROUP BY ROOMTYPE
ORDER BY COUNT(ROOM.ROOMTYPE) DESC;